# Generated by Django 3.2.7 on 2022-02-03 14:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('film', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='videoreview',
            name='like',
            field=models.CharField(choices=[('like', 'like'), ('dislike', 'dislike')], default=' ', max_length=10),
            preserve_default=False,
        ),
    ]
