# Generated by Django 3.2.7 on 2022-02-03 15:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('film', '0002_videoreview_like'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='videoreview',
            name='like',
        ),
        migrations.AddField(
            model_name='videoreview',
            name='likes',
            field=models.PositiveSmallIntegerField(default=0),
        ),
    ]
