# Generated by Django 3.2.7 on 2022-02-03 09:11

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('film', '0003_alter_videoreview_rating'),
    ]

    operations = [
        migrations.AlterField(
            model_name='videoreview',
            name='rating',
            field=models.PositiveIntegerField(default=1, validators=[django.core.validators.MaxValueValidator(5), django.core.validators.MinValueValidator(1)]),
        ),
    ]
