# Generated by Django 3.2.7 on 2022-02-03 19:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('film', '0005_auto_20220203_1928'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='video',
            name='dislikes',
        ),
    ]
