# Generated by Django 3.2.7 on 2022-02-04 03:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('film', '0006_remove_video_dislikes'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='video',
            name='likes',
        ),
        migrations.AddField(
            model_name='video',
            name='body',
            field=models.CharField(default='', max_length=140),
            preserve_default=False,
        ),
    ]
